# Generated by Django 4.1.1 on 2022-10-18 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produk',
            new_name='Mahasiswa',
        ),
    ]
