# Generated by Django 4.1.1 on 2022-12-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_berita_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='berita',
            name='nama',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
