# Generated by Django 4.1.1 on 2022-10-18 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_rename_produk_mahasiswa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mahasiswa',
            old_name='prdi',
            new_name='prodi',
        ),
    ]
