# Generated by Django 4.1.1 on 2022-12-23 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_alter_berita_nama'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='berita',
            name='image',
        ),
    ]
